// This file is generated by `flutterfire configure`.
// Run: dart pub global activate flutterfire_cli && flutterfire configure
//
// DO NOT edit manually.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Replace these with values from your Firebase project console
  // after running: flutterfire configure

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiNRIyjk7tfW1_OjwsAMmHZJVm2sutcdg',
    appId: '1:148021503887:web:f7ea74969d08a0c45a0dfa',
    messagingSenderId: '148021503887',
    projectId: 'mborba-proyect',
    authDomain: 'mborba-proyect.firebaseapp.com',
    storageBucket: 'mborba-proyect.firebasestorage.app',
    measurementId: 'G-8B88HQ1L1M',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYgne7av-CKtIhDMGBWC1c5shUte7VhOo',
    appId: '1:148021503887:android:0d0b769567e121275a0dfa',
    messagingSenderId: '148021503887',
    projectId: 'mborba-proyect',
    storageBucket: 'mborba-proyect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9uBVHcEomOwJln7x7V6PrUSxPV7sc1LI',
    appId: '1:148021503887:ios:dbabf732af2d791a5a0dfa',
    messagingSenderId: '148021503887',
    projectId: 'mborba-proyect',
    storageBucket: 'mborba-proyect.firebasestorage.app',
    iosBundleId: 'com.example.receiptAiFinanceAssistant',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9uBVHcEomOwJln7x7V6PrUSxPV7sc1LI',
    appId: '1:148021503887:ios:dbabf732af2d791a5a0dfa',
    messagingSenderId: '148021503887',
    projectId: 'mborba-proyect',
    storageBucket: 'mborba-proyect.firebasestorage.app',
    iosBundleId: 'com.example.receiptAiFinanceAssistant',
  );
}
