import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../../shared/theme/app_colors.dart';
import '../../../../shared/widgets/loading_indicator.dart';
import '../../domain/entities/insight_entity.dart';
import '../providers/insights_provider.dart';

class InsightsScreen extends ConsumerWidget {
  const InsightsScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final insightsAsync = ref.watch(monthlyInsightsProvider);

    return Scaffold(
      appBar: AppBar(
        title: const Text('AI Insights'),
        actions: [
          IconButton(
            icon: const Icon(Icons.refresh_outlined),
            onPressed: () => ref.invalidate(monthlyInsightsProvider),
          ),
        ],
      ),
      body: insightsAsync.when(
        data: (insights) => insights.isEmpty
            ? _buildEmptyState(context)
            : _buildInsights(context, insights),
        loading: () => const Padding(
          padding: EdgeInsets.all(16),
          child: ShimmerList(count: 4, itemHeight: 120),
        ),
        error: (e, _) => _buildErrorState(context, e.toString(), ref),
      ),
    );
  }

  Widget _buildInsights(BuildContext context, List<InsightEntity> insights) {
    return ListView(
      padding: const EdgeInsets.all(16),
      children: [
        _buildHeader(context),
        const SizedBox(height: 16),
        ...insights.map((insight) => Padding(
              padding: const EdgeInsets.only(bottom: 12),
              child: InsightCard(insight: insight),
            )),
        const SizedBox(height: 16),
        _buildFooter(context),
      ],
    );
  }

  Widget _buildHeader(BuildContext context) {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Row(
          children: [
            Container(
              padding: const EdgeInsets.all(10),
              decoration: BoxDecoration(
                gradient: const LinearGradient(
                  colors: [AppColors.primary, AppColors.accent],
                ),
                borderRadius: BorderRadius.circular(12),
              ),
              child: const Icon(Icons.auto_awesome, color: Colors.white, size: 20),
            ),
            const SizedBox(width: 14),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text('This month\'s insights', style: Theme.of(context).textTheme.titleMedium),
                  Text(
                    'Generated by AI based on your spending',
                    style: Theme.of(context).textTheme.bodySmall,
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildFooter(BuildContext context) {
    return Text(
      'Insights are generated by an AI model and may not always be accurate. Use as guidance only.',
      textAlign: TextAlign.center,
      style: Theme.of(context).textTheme.bodySmall?.copyWith(fontSize: 11),
    );
  }

  Widget _buildEmptyState(BuildContext context) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(32),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Icon(Icons.lightbulb_outline, size: 64, color: AppColors.textMuted),
            const SizedBox(height: 16),
            Text('No insights yet', style: Theme.of(context).textTheme.titleMedium),
            const SizedBox(height: 8),
            Text(
              'Add more receipts this month to generate AI-powered insights about your spending patterns.',
              textAlign: TextAlign.center,
              style: Theme.of(context).textTheme.bodyMedium,
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildErrorState(BuildContext context, String error, WidgetRef ref) {
    final isConnError = error.toLowerCase().contains('connection') ||
        error.toLowerCase().contains('socket');

    return Center(
      child: Padding(
        padding: const EdgeInsets.all(32),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Icon(Icons.cloud_off_outlined, size: 48, color: AppColors.warning),
            const SizedBox(height: 16),
            Text(
              isConnError
                  ? 'Could not reach AI provider'
                  : 'Failed to generate insights',
              style: Theme.of(context).textTheme.titleMedium,
            ),
            const SizedBox(height: 8),
            if (isConnError)
              Text(
                'Make sure Ollama is running locally:\nollama serve',
                textAlign: TextAlign.center,
                style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                      fontFamily: 'monospace',
                    ),
              ),
            const SizedBox(height: 16),
            TextButton(
              onPressed: () => ref.invalidate(monthlyInsightsProvider),
              child: const Text('Retry'),
            ),
          ],
        ),
      ),
    );
  }
}

class InsightCard extends StatelessWidget {
  final InsightEntity insight;
  const InsightCard({super.key, required this.insight});

  @override
  Widget build(BuildContext context) {
    final (borderColor, bgColor) = switch (insight.type) {
      InsightType.warning => (AppColors.error, AppColors.error.withOpacity(0.05)),
      InsightType.saving => (AppColors.success, AppColors.success.withOpacity(0.05)),
      InsightType.behavior => (AppColors.warning, AppColors.warning.withOpacity(0.05)),
      InsightType.pattern => (AppColors.primary, AppColors.primary.withOpacity(0.05)),
    };

    return Container(
      decoration: BoxDecoration(
        color: bgColor,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: borderColor.withOpacity(0.3)),
      ),
      padding: const EdgeInsets.all(16),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(insight.icon, style: const TextStyle(fontSize: 28)),
          const SizedBox(width: 14),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  children: [
                    Expanded(
                      child: Text(
                        insight.title,
                        style: Theme.of(context).textTheme.titleMedium,
                      ),
                    ),
                    _TypeChip(type: insight.type, color: borderColor),
                  ],
                ),
                const SizedBox(height: 8),
                Text(insight.description, style: Theme.of(context).textTheme.bodyMedium),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class _TypeChip extends StatelessWidget {
  final InsightType type;
  final Color color;

  const _TypeChip({required this.type, required this.color});

  @override
  Widget build(BuildContext context) {
    final label = switch (type) {
      InsightType.pattern => 'Pattern',
      InsightType.saving => 'Saving',
      InsightType.behavior => 'Behavior',
      InsightType.warning => 'Warning',
    };

    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
      decoration: BoxDecoration(
        color: color.withOpacity(0.15),
        borderRadius: BorderRadius.circular(20),
      ),
      child: Text(
        label,
        style: TextStyle(color: color, fontSize: 11, fontWeight: FontWeight.w600),
      ),
    );
  }
}
